config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users
  resources :pizzas
  resources :toppings
  resources :toppings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

class User < ApplicationRecord
  # So here, you can call `enum` 
  #enum role: { chef: 0, owner: 1 }
end

app/models/pizza.rb
class Pizza < ApplicationRecord
    has_and_belongs_to_many :toppings
  
    validates :name, presence: true, uniqueness: true
  
    private
  
    def unique_toppings
      toppings_set = toppings.map(&:id).sort
      if Pizza.joins(:toppings).where(toppings: { id: toppings_set }).exists?
        errors.add(:toppings, "A pizza with the same toppings already exists")
      end
    end
  end
  

app/models/topping.rb
class Topping < ApplicationRecord
    has_and_belongs_to_many :pizzas

    validates :name, presence: true, uniqueness: true
  end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #enum role: { chef: 0, owner: 1 }

  def owner?
    role == "owner"
  end
  
  def chef?
    role == "chef"
  end
  
end


# app/models/user.rb
#class User < ApplicationRecord
  # Devise modules already inserted by the generator
  # e.g. devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

#  
#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # Add this line to define @pizzas
    @pizzas = Pizza.all
  end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
    before_action :set_pizza, only: [:show, :edit, :update, :destroy]
  
    def index
      @pizzas = Pizza.all
    end
  
    def show; end
  
    def new
      @pizza = Pizza.new
      @toppings = Topping.all
    end
  
    def create
      @pizza = Pizza.new(pizza_params)
      if @pizza.save
        redirect_to @pizza, notice: 'Pizza was successfully created.'
      else
        @toppings = Topping.all
        render :new
      end
    end
  
    def edit
      @toppings = Topping.all
    end
  
    def update
      if @pizza.update(pizza_params)
        redirect_to @pizza, notice: 'Pizza was successfully updated.'
      else
        @toppings = Topping.all
        render :edit
      end
    end
  
    def destroy
      @pizza.destroy
      redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.'
    end
  
    private
  
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end
  
    def pizza_params
      params.require(:pizza).permit(:name, topping_ids: [])
    end
  end
  

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_owner!, only: [:new, :create, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @toppings = Topping.all
  end

  def new
    @topping = Topping.new
  end  

  def create
    @topping = Topping.new(topping_params)
    if @topping.save
      # When the Topping successfully saves, redirect wherever you like:
      redirect_to toppings_path, notice: "Topping created successfully!"
    else
      # If validation fails, re-render the form
      render :new, status: :unprocessable_entity
    end
  end

  def show
    # @topping is set by the `set_topping` method
  end

  def edit
    # @topping is set by the `set_topping` method
  end

  def update
    if @topping.update(topping_params)
      redirect_to topping_path(@topping), notice: "Topping was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @topping.destroy
    redirect_to toppings_path, notice: "Topping was successfully deleted."
  end

  private

  def set_topping
    @topping = Topping.find(params[:id])
  end

  def topping_params
    params.require(:topping).permit(:name)
  end

  def authorize_owner!
    # Use current_user (from Devise)
    unless current_user.owner?
      redirect_to toppings_path, alert: "You don't have permission to modify Toppings!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/views/home/index.html.erb
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


<div class="container my-5">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">PizzaApp</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pizzas", pizzas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Toppings", toppings_path, class: "nav-link" %>
          </li>
        </ul>

        <!-- Right-aligned navbar items -->
        <ul class="navbar-nav ms-auto">
          <!-- Account Dropdown -->
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <!-- Dropdown toggle shows "Account" if user is logged in -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </li>
              </ul>
            <% else %>
              <!-- Dropdown toggle shows "Sign In" if user is logged out -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Sign In
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                </li>
              </ul>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>



<div class="container my-5">
  <h1 class="mb-4">Welcome to the StrongMind Pizza Manager</h1>

  <div class="d-flex justify-content-between mb-3">
    <%= link_to 'Create a New Pizza', new_pizza_path, class: 'btn btn-primary' %>

  </div>

  <table class="table table-bordered table-striped">
    <thead class="table-dark">
      <tr>
        <th>Pizza Name</th>
        <th>Toppings</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @pizzas.each do |pizza| %>
        <tr>
          <td><%= pizza.name %></td>
          <td>
            <% if pizza.toppings.any? %>
              <%= pizza.toppings.map(&:name).join(', ') %>
            <% else %>
              <em>No Toppings</em>
            <% end %>
          </td>
          <td>
            <%= link_to 'View', pizza_path(pizza), class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_pizza_path(pizza), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Delete', pizza_path(pizza), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pizzas/index.html.erb
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


<div class="container my-5">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">PizzaApp</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pizzas", pizzas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Toppings", toppings_path, class: "nav-link" %>
          </li>
        </ul>

        <!-- Right-aligned navbar items -->
        <ul class="navbar-nav ms-auto">
          <!-- Account Dropdown -->
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <!-- Dropdown toggle shows "Account" if user is logged in -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </li>
              </ul>
            <% else %>
              <!-- Dropdown toggle shows "Sign In" if user is logged out -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Sign In
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                </li>
              </ul>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>


<h1>StrongMind Pizzas</h1>

<div class="container my-5">

  <div class="d-flex justify-content-between mb-3">
    <%= link_to 'New Pizza', new_pizza_path, class: 'btn btn-primary' %>
    <%= link_to 'Back to Home', root_path, class: 'btn btn-secondary' %>
  </div>

  <table class="table table-bordered table-striped">
    <thead class="table-dark">
      <tr>
        <th>Pizza Name</th>
        <th>Toppings</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @pizzas.each do |pizza| %>
        <tr>
          <td><%= pizza.name %></td>
          <td>
            <% if pizza.toppings.any? %>
              <%= pizza.toppings.map(&:name).join(', ') %>
            <% else %>
              <em>No Toppings</em>
            <% end %>
          </td>
          <td>
            <%= link_to 'View', pizza_path(pizza), class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_pizza_path(pizza), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Delete', pizza_path(pizza), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>

      

app/views/pizzas/new.html.erb
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


<div class="container my-5">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">PizzaApp</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pizzas", pizzas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Toppings", toppings_path, class: "nav-link" %>
          </li>
        </ul>

        <!-- Right-aligned navbar items -->
        <ul class="navbar-nav ms-auto">
          <!-- Account Dropdown -->
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <!-- Dropdown toggle shows "Account" if user is logged in -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </li>
              </ul>
            <% else %>
              <!-- Dropdown toggle shows "Sign In" if user is logged out -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Sign In
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                </li>
              </ul>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>


<div class="container my-5">
  <h1 class="mb-4">New Pizza</h1>

  <%= form_with model: @pizza, local: true, html: { class: "card p-4 shadow" } do |form| %>
    <div class="mb-3">
      <%= form.label :name, "Pizza Name", class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-4">
      <h3>Select Toppings</h3>
      <%= link_to 'Add New Topping', new_topping_path, class: 'btn btn-primary btn-sm mb-3' %>
      <div class="form-check">
        <% @toppings.each do |topping| %>
          <div class="mb-1">
            <%= check_box_tag 'pizza[topping_ids][]', topping.id, @pizza.toppings.include?(topping), class: "form-check-input" %>
            <%= label_tag "pizza_topping_#{topping.id}", topping.name, class: "form-check-label" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="d-flex justify-content-between">
      <%= form.submit 'Create Pizza', class: "btn btn-success" %>

    </div>
  <% end %>
  <div>
    <%= link_to 'View all Pizzas', pizzas_path, class: 'btn btn-secondary' %>
  <%= link_to 'Back to Home', root_path, class: 'btn btn-primary mt-3' %>
  </div>
</div>

app/views/pizzas/show.html.erb
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


<div class="container my-5">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">PizzaApp</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pizzas", pizzas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Toppings", toppings_path, class: "nav-link" %>
          </li>
        </ul>

        <!-- Right-aligned navbar items -->
        <ul class="navbar-nav ms-auto">
          <!-- Account Dropdown -->
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <!-- Dropdown toggle shows "Account" if user is logged in -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </li>
              </ul>
            <% else %>
              <!-- Dropdown toggle shows "Sign In" if user is logged out -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Sign In
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                </li>
              </ul>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

  <div class="card p-4 shadow">
    <h2><%= @pizza.name %></h2>
    <h3 class="mt-3">Toppings:</h3>
    <% if @pizza.toppings.any? %>
      <ul>
        <% @pizza.toppings.each do |topping| %>
          <li><%= topping.name %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No toppings added to this pizza.</p>
    <% end %>
  </div>

  <div class="mt-4">
    <%= link_to 'Edit Pizza', edit_pizza_path(@pizza), class: 'btn btn-warning' %>
    <%= button_to "Delete Pizza", pizza_path(@pizza), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <%= link_to 'Back to Pizzas', pizzas_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/toppings/index.html.erb
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


<div class="container my-5">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">PizzaApp</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pizzas", pizzas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Toppings", toppings_path, class: "nav-link" %>
          </li>
        </ul>

        <!-- Right-aligned navbar items -->
        <ul class="navbar-nav ms-auto">
          <!-- Account Dropdown -->
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <!-- Dropdown toggle shows "Account" if user is logged in -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </li>
              </ul>
            <% else %>
              <!-- Dropdown toggle shows "Sign In" if user is logged out -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Sign In
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                </li>
              </ul>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>


<div class="container my-5">
  <h1 class="mb-4">StrongMind Toppings</h1>

  <div class="d-flex justify-content-between mb-3">
    <%= link_to 'New Topping', new_topping_path, class: 'btn btn-primary' %>
    <%= link_to 'Back to Home', root_path, class: 'btn btn-secondary' %>
  </div>

  <table class="table table-bordered table-striped">
    <thead class="table-dark">
      <tr>
        <th>Topping Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @toppings.each do |topping| %>
        <tr>
          <td><%= topping.name %></td>
          <td>
            <%= link_to 'Edit', edit_topping_path(topping), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Delete', topping_path(topping), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/toppings/show.html.erb
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


<div class="container my-5">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">PizzaApp</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pizzas", pizzas_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Toppings", toppings_path, class: "nav-link" %>
          </li>
        </ul>

        <!-- Right-aligned navbar items -->
        <ul class="navbar-nav ms-auto">
          <!-- Account Dropdown -->
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <!-- Dropdown toggle shows "Account" if user is logged in -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </li>
              </ul>
            <% else %>
              <!-- Dropdown toggle shows "Sign In" if user is logged out -->
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false">
                Sign In
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
                </li>
              </ul>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>


<div class="container my-5">
  <h1 class="mb-4">Topping Details</h1>

  <div class="card p-4 shadow">
    <h2><%= @topping.name %></h2>
    <p class="mt-3">This topping is used in the following pizzas:</p>
    <% if @topping.pizzas.any? %>
      <ul>
        <% @topping.pizzas.each do |pizza| %>
          <li><%= link_to pizza.name, pizza_path(pizza), class: "btn btn-link" %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No pizzas currently use this topping.</p>
    <% end %>
  </div>

  <div class="mt-4">
    <%= link_to 'Edit Topping', edit_topping_path(@topping), class: 'btn btn-warning' %>
    <%= button_to "Delete Topping", topping_path(@topping), 
                  method: :delete, 
                  data: { turbo_confirm: "Are you sure you want to delete this topping?" }, 
                  class: "btn btn-danger" %>
    <%= link_to 'Back to Toppings', toppings_path, class: 'btn btn-secondary' %>
  </div>
</div>